[package]
name = "image-processing"
version = "0.1.0"
authors = ["Dimitar Lukanov <dimiturlukanov@gmail.com>"]

[dependencies]
image = "*"
gtk = { version = "0.5.0", features = ["v3_10"] }
gdk-pixbuf = "0.5.0"
failure = "0.1.5"